
TG_CAT_HIDES = "Hides";

TG_DB_HIDES = {
  { tag = "769" , name = "Chunk of Boar Meat" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "783" , name = "Light Hide" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "2318" , name = "Light Leather" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "2319" , name = "Medium Leather" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "2589" , name = "Linen Cloth" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "2672" , name = "Stringy Wolf Meat" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "2675" , name = "Crawler Claw" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "2934" , name = "Ruined Leather Scraps" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "4232" , name = "Medium Hide" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "4234" , name = "Heavy Leather" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "4235" , name = "Heavy Hide" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "4304" , name = "Thick Leather" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "5465" , name = "Small Spider Leg" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "6470" , name = "Deviate Scale" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "6471" , name = "Perfect Deviate Scale" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "7286" , name = "Black Whelp Scale" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "7392" , name = "Green Whelp Scale" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "8154" , name = "Scorpid Scale" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "8165" , name = "Worn Dragonscale" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "8167" , name = "Turtle Scale" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "8169" , name = "Thick Hide" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "8170" , name = "Rugged Leather" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "8171" , name = "Rugged Hide" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "12607" , name = "Brilliant Chromatic Scale" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "15408" , name = "Heavy Scorpid Scale" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "15410" , name = "Scale of Onyxia" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "15412" , name = "Green Dragonscale" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "15414" , name = "Red Dragonscale" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "15415" , name = "Blue Dragonscale" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "15416" , name = "Black Dragonscale" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "15417" , name = "Devilsaur Leather" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "15419" , name = "Warbear Leather" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "17012" , name = "Core Leather" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "21887" , name = "Knothide Leather" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "25649" , name = "Knothide Leather Scraps" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "25699" , name = "Crystal Infused Leather" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "25700" , name = "Fel Scales" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "25707" , name = "Fel Hide" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "25708" , name = "Thick Clefthoof Leather" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "29539" , name = "Cobra Scales" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "29547" , name = "Wind Scales" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "29548" , name = "Nether Dragonscales" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "33567" , name = "Borean Leather Scraps" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "33568" , name = "Borean Leather" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "38557" , name = "Icy Dragonscale" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "38558" , name = "Nerubian Chitin" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "38561" , name = "Jormungar Scale" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "44128" , name = "Arctic Fur" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "52976" , name = "Savage Leather" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "52977" , name = "Savage Leather Scraps" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "52979" , name = "Blackened Dragonscale" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "52982" , name = "Deepsea Scale" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "60224" , name = "Handful of Obsidium Bolts" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "67749" , name = "Electrified Ether" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "72120" , name = "Exotic Leather" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "72162" , name = "Sha-Touched Leather" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "72163" , name = "Magnificent Hide" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "72234" , name = "Green Tea Leaf" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "72235" , name = "Silkweed" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "72237" , name = "Rain Poppy" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "79010" , name = "Snow Lily" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "79101" , name = "Prismatic Scale" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "109624" , name = "Broken Frostweed Stem" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "110609" , name = "Raw Beast Hide" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "110610" , name = "Raw Beast Hide Scraps" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "112155" , name = "Deepsea Scale Fragment" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "112156" , name = "Blackened Dragonscale Fragment" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "112157" , name = "Prismatic Scale Fragment" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "112158" , name = "Icy Dragonscale Fragment" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "112177" , name = "Nerubian Chitin Fragment" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "112182" , name = "Patch of Fel Hide" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "112185" , name = "Wind Scale Fragment" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "120945" , name = "Primal Spirit" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "124113" , name = "Stonehide Leather" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "124115" , name = "Stormscale" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "124117" , name = "Lean Shank" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "124118" , name = "Fatty Bearsteak" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "124119" , name = "Big Gamy Ribs" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "124120" , name = "Leyblood" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "124124" , name = "Blood of Sargeras" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "124438" , name = "Unbroken Claw" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "124439" , name = "Unbroken Tooth" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "127759" , name = "Felblight" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "151566" , name = "Fiendish Leather" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "151568" , name = "Primal Sargerite" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "152541" , name = "Coarse Leather" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "152631" , name = "Briny Flesh" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "153050" , name = "Shimmerscale" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "153051" , name = "Mistscale" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "154164" , name = "Blood-Stained Bone" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "154165" , name = "Calcified Bone" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "154722" , name = "Tempest Hide" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "154897" , name = "Stringy Loins" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "154898" , name = "Meaty Haunch" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "154899" , name = "Thick Paleo Steak" , cat = TG_CAT_HIDES, skill = 1},
  { tag = "160502" , name = "Chemical Blasting Cap" , cat = TG_CAT_HIDES, skill = 1},

}

TGS_PLUGIN_CATEGORIES = {
    { db = TG_DB_HIDES, name = TG_CAT_HIDES,        smenu = TG_PREFIX_SHOW..TG_CAT_HIDES,       profession = "Skinning", cat = TG_CAT_HIDES, skill = 1},
}

TGS_SKINABLES = {}